In this notebook we'll be working on the Exploratory Data Analysis of the dataset created in the previous notebook. We'll try to respond to the business requests, such as identifying the "best Italian Municipalities for strategic investment", discovering what towns have the highest accident rates, total accidents, etc.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
df_incidents = pd.read_csv("data/traffic_incidents.csv")
df_municipalities = pd.read_csv("data/municipalities_metrics.csv")
df_aci = pd.read_csv("data/aci_fleet.csv")

In [7]:
#a quick check 
df_incidents.info()

<class 'pandas.DataFrame'>
RangeIndex: 257715 entries, 0 to 257714
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   REF_AREA        257715 non-null  int64
 1   DATA_TYPE       257715 non-null  str
 2   RESULT          257715 non-null  str
 3   TIME_PERIOD     257715 non-null  int64
 4   OBS_VALUE       257715 non-null  int64
 5   Codice_Regione  257715 non-null  int64
 6   Comune          257682 non-null  str
 7   Regione         257715 non-null  str
dtypes: int64(4), str(4)
memory usage: 15.7 MB

In [10]:
#After checking the data, we discovered that the municipality with code 1168 is a town named None. This specific name caused an anomaly as Pandas parsed the string "None" as a missing value (NaN). 
#We will add the keep_default_na=False argoument.
df_incidents[df_incidents["Comune"].isna()]

,REF_AREA,DATA_TYPE,RESULT,TIME_PERIOD,OBS_VALUE,Codice_Regione,Comune,Regione
5325,1168,KILLINJ,F,2014,15,1,NaN,Piemonte
5326,1168,KILLINJ,F,2015,14,1,NaN,Piemonte
5327,1168,KILLINJ,F,2016,14,1,NaN,Piemonte
5328,1168,KILLINJ,F,2017,25,1,NaN,Piemonte
5329,1168,KILLINJ,F,2018,14,1,NaN,Piemonte
5330,1168,KILLINJ,F,2019,11,1,NaN,Piemonte
5331,1168,KILLINJ,F,2020,11,1,NaN,Piemonte
5332,1168,KILLINJ,F,2021,11,1,NaN,Piemonte
5333,1168,KILLINJ,F,2022,10,1,NaN,Piemonte
5334,1168,KILLINJ,F,2023,9,1,NaN,Piemonte
5335,1168,KILLINJ,F,2024,7,1,NaN,Piemonte
5336,1168,KILLINJ,M,2014,0,1,NaN,Piemonte
5337,1168,KILLINJ,M,2015,2,1,NaN,Piemonte
5338,1168,KILLINJ,M,2016,1,1,NaN,Piemonte
5339,1168,KILLINJ,M,2017,2,1,NaN,Piemonte
5340,1168,KILLINJ,M,2018,0,1,NaN,Piemonte
5341,1168,KILLINJ,M,2019,0,1,NaN,Piemonte
5342,1168,KILLINJ,M,2020,0,1,NaN,Piemonte
5343,1168,KILLINJ,M,2021,0,1,NaN,Piemonte
5344,1168,KILLINJ,M,2022,0,1,NaN,Piemonte
5345,1168,KILLINJ,M,2023,0,1,NaN,Piemonte
5346,1168,KILLINJ,M,2024,0,1,NaN,Piemonte
5347,1168,ROADACC,9,2014,13,1,NaN,Piemonte
5348,1168,ROADACC,9,2015,11,1,NaN,Piemonte
5349,1168,ROADACC,9,2016,11,1,NaN,Piemonte
5350,1168,ROADACC,9,2017,16,1,NaN,Piemonte
5351,1168,ROADACC,9,2018,7,1,NaN,Piemonte
5352,1168,ROADACC,9,2019,9,1,NaN,Piemonte
5353,1168,ROADACC,9,2020,8,1,NaN,Piemonte
5354,1168,ROADACC,9,2021,9,1,NaN,Piemonte
5355,1168,ROADACC,9,2022,7,1,NaN,Piemonte
5356,1168,ROADACC,9,2023,7,1,NaN,Piemonte
5357,1168,ROADACC,9,2024,5,1,NaN,Piemonte

In [11]:
df_incidents = pd.read_csv("data/traffic_incidents.csv", keep_default_na=False)
df_incidents.info()

<class 'pandas.DataFrame'>
RangeIndex: 257715 entries, 0 to 257714
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   REF_AREA        257715 non-null  int64
 1   DATA_TYPE       257715 non-null  str
 2   RESULT          257715 non-null  str
 3   TIME_PERIOD     257715 non-null  int64
 4   OBS_VALUE       257715 non-null  int64
 5   Codice_Regione  257715 non-null  int64
 6   Comune          257715 non-null  str
 7   Regione         257715 non-null  str
dtypes: int64(4), str(4)
memory usage: 15.7 MB

In [14]:
df_municipalities = pd.read_csv("data/municipalities_metrics.csv", keep_default_na=False)
df_municipalities.info()

<class 'pandas.DataFrame'>
RangeIndex: 7896 entries, 0 to 7895
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Codice_Regione      7896 non-null   int64
 1   Codice_Comune       7896 non-null   int64
 2   Comune              7896 non-null   str
 3   Popolazione_Legale  7896 non-null   int64
 4   Superficie(Kmq)     7896 non-null   float64
 5   Regione             7896 non-null   str
dtypes: float64(1), int64(3), str(2)
memory usage: 370.3 KB

In [17]:
df_aci

           Regione Parco_Auto_2024
0         Piemonte       3.075.162
1    Valle D'Aosta         237.162
2        Lombardia       6.426.326
3    Trentino A.A.       1.291.248
4           Veneto       3.302.750
5      Friuli V.G.         828.929
6          Liguria         850.098
7   Emilia Romagna       3.082.830
8          Toscana       2.722.906
9           Umbria         659.203
10          Marche       1.063.668
11           Lazio       4.000.575
12         Abruzzo         923.548
13          Molise         220.815
14        Campania       3.725.175
15          Puglia       2.515.558
16      Basilicata         391.305
17        Calabria       1.376.514
18         Sicilia       3.508.207
19        Sardegna       1.122.826

In [21]:
#we can change the datatype for the "Parco_Auto_2024" columns into int64
df_aci["Parco_Auto_2024"] = df_aci["Parco_Auto_2024"].astype(str).str.replace(".", "").astype(int)
df_aci.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Regione          20 non-null     str
 1   Parco_Auto_2024  20 non-null     int64
dtypes: int64(1), str(1)
memory usage: 452.0 bytes

We can now proceed with further dataset manipulation, trying to create three distinct columns for the "DATA_TYPE" column